name: NOVA
favicon: null
layout_spectrum: 0.2468466297723353
typography_spectrum: 0.7536434468347579
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.045510597759857774
  lightness: 0.6031519609969109
  saturation: 0.7964483990799636
  rhythmicContrast: 0.11893037846311927
purpose: []
